# Generated by Django 5.1 on 2025-02-05 20:02

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MealType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/')),
                ('recipe', models.URLField(blank=True, help_text='Enter a valid URL, e.g., https://example.com', max_length=500, null=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('vegeterian', models.BooleanField(default=False)),
                ('grandma', models.BooleanField(default=False)),
                ('meal_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='entries.mealtype')),
            ],
        ),
    ]
