# Generated by Django 5.1 on 2025-02-19 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0002_alter_meal_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='notes',
            field=models.TextField(blank=True, help_text='e.g. recipe notes.', max_length=500, verbose_name='Notes'),
        ),
    ]
