# Generated by Django 5.1 on 2025-11-04 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0003_meal_notes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meal',
            old_name='vegeterian',
            new_name='vegetarian',
        ),
    ]
