# Generated by Django 5.1 on 2025-11-11 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0004_rename_vegeterian_meal_vegetarian'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='media/uploads/'),
        ),
    ]
